export const Branches = [
  "Aerospace Engineering (AE)",
  "Biological Sciences and Bioengineering (BSBE)",
  "Civil Engineering (CE)",
  "Chemical Engineering (CHE)",
  "Computer Science and Engineering (CSE)",
  "Electrical Engineering (EE)",
  "Material Science and Engineering (MSE)",
  "Mechanical Engineering (ME)",
  "Chemistry (CHM)",
  "Economics (ECO)",
  "Earth Sciences (ES)",
  "Mathematics and Scientific Computing (MTH)",
  "Statistics and Data Science (SDS)",
  "Physics (PHY)",
  "Cognitive Science (CGS)",
  "Design (DES)",
  "Management Studies (MS)",
  "Materials Science Programme (MSP)",
  "Nuclear Engineering and Technology (NET)",
  "Photonics Science and Engineering (PSE)",
  "Statistics (Stats)",
  "Humanities and Social Sciences (HSS)",
  "Mathematics",
  "Sustainable Energy Engineering (SEE)",
  "Space Science and Astronomy (SSA)",
];

export const Hostels = [
  "Hall 1",
  "Hall 2",
  "Hall 3",
  "Hall 4",
  "Hall 5",
  "Hall 6",
  "Hall 7",
  "Hall 8",
  "Hall 9",
  "Hall 10",
  "Hall 11",
  "Hall 12",
  "Hall 13",
  "Hall 14",
];
